language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
#  - "nightly"

sudo: false

install:
  - pip install -r requirements-dev.txt

script:
  - nosetests --with-coverage --cover-package=acapi2
  - flake8

after_success:
  - codecov
